version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Lovanky6408
      POSTGRES_DB: remkey
    ports:
      - "5432:5432"

#redis
  redis:
    image: redis:7-alpine
    container_name: remkey-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
